#!/bin/bash
# alternative descriptor (3~9)

exec 3>customRedirectOutput

echo "This should display on the monitor"
echo "and this should be sotred in the file">&3
echo "Then this should be back on the monitor"
