#!/bin/bash
# 모니터로 가야할 output이 file로

exec 3>&1
exec 1>tempRedirectOutput

echo "This should store in the output file"
echo "along with this linke"

exec 1>&3

echo "Now things should be back to normla"
